default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vue2_development

test:
  <<: *default
  database: vue2_test

production:
  <<: *default
  database: vue2_production
  username: vue2
  password: <%= ENV['VUE2_DATABASE_PASSWORD'] %>
